baseURL = 'https://www.landerwells.com/'
locale = 'en-US'
title = "Lander's blog"

refLinksErrorLevel = 'warning'
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  email = "landerwells@gmail.com"
  github = "https://github.com/landerwells"
  linkedin = "https://www.linkedin.com/in/landerwells"

  [params.umami]
    website_id = "0a89cc5d-0bb0-4d45-bb17-324c3b7f2e71"
    script_url = "https://cloud.umami.is/script.js"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    noClasses = false

[frontmatter]
  lastmod = [":git", ":fileModTime", "lastmod"]
  publishDate = ['publishDate']

[[menu.main]]
    name = "landerwells@gmail.com"
    url = "/"
    weight = 1

[[menu.main]]
    name = "blog"
    url = "/blog"
    weight = 2

[[menu.main]]
    name = "notes"
    url = "/notes"
    weight = 3

[[menu.main]]
    name = "github"
    url = "https://github.com/landerwells"
    weight = 4

[[menu.main]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/landerwells"
    weight = 5

[[menu.main]]
    name = "RSS"
    url = "/blog/index.xml"
    weight = 6
