baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Lander's blog"
theme = ['hugo-bearblog']

refLinksErrorLevel = 'warning'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  email = "landerwells@gmail.com"
  github = "https://github.com/landerwells"
  linkedin = "https://www.linkedin.com/in/landerwells"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    style = "solarized-dark"
    noClasses = true

[frontmatter]
  lastmod = [":git", ":fileModTime", "lastmod"]
  publishDate = ['publishDate']

[[menu.main]]
    name = "landerwells@gmail.com"
    url = "/"
    weight = 1

[[menu.main]]
    name = "blog"
    url = "/blog"
    weight = 2

[[menu.main]]
    name = "notes"
    url = "/notes"
    weight = 3

[[menu.main]]
    name = "github"
    url = "https://github.com/landerwells"
    weight = 4

[[menu.main]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/landerwells"
    weight = 5

[[menu.main]]
    name = "RSS"
    url = "/blog/index.xml"
    weight = 6
